layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "thoughts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

collections: 
  thoughts: 
    output: true
    layout: "post"

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  linkedin: riley-molloy-04606196
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: rpm4real
  # youtube: your_username
  # instagram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url

topics:
  - name: Python
    web_url: https://github.com/topics/python
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Spark and Scala
    web_url: https://www.scala-lang.org/ 
    image_url: https://www.scala-lang.org/resources/img/frontpage/scala-logo-white@2x.png

  - name: Mathematics
    

theme: jekyll-theme-slate